[package]
name = "rstocks"
version = "0.1.0"
authors = ["anon767 <anon767@thecout.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

